### ISSUE TITLE
No source code.....

### ISSUE THREAD

**Issue by PySimpleGUI** [PriestTheBeast/SimpleGUIBuilder#1]
All of the files marked with "Source Code" only have the readme.

![image](https://user-images.githubusercontent.com/46163555/105646309-3b0bb000-5e6d-11eb-9145-09721d6b8f5f.png)

**Comment by PriestTheBeast** [comment]
The reason:
https://www.reddit.com/r/Python/comments/l46dz4/simpleguibuilder_a_gui_for_designing_python_guis/gkndyse/
It only has readme because that's the only thing in this github. At least for now.

**Comment by PySimpleGUI** [comment]
Hmmmm... I still don't understand, but, it's your repo.

**Comment by 2br-2b** [comment]
Honestly, even if the source code is lacking in organization, at least this way, people can see the code and begin to help with it. For example, right now, I can't run it in Linux without using Wine, but if I had the source code, I could probably run it. Besides that, thanks for releasing this tool! It'll be super useful for me to start learning about making Python guis!

**Comment by PySimpleGUI** [comment]
Have you seen the comments in the PySimpleGUI code about how embarrassed I am about it... that I'm not very experienced in Python, etc?   It'll be ok.... honest....

**Comment by 2br-2b** [comment]
All right :-)

Thanks for making the tool anyway! Great job bringing a python project through to completion, and have fun continuing to learn and get better!

**Comment by PriestTheBeast** [comment]
Sry for leaving you guys hanging. I'm at work right now, but I intended and intend to do some quick refactoring and put the code here :)
Thx for the support!

**Comment by PySimpleGUI** [comment]
I'm sorry.... I don't mean to be pushy.  You take your time.  Do what you feel comfortable with.  Everyone is different.

**Comment by PriestTheBeast** [comment]
Don't worry you weren't pushy. This was something I was already considering too. Although most part of the code is really just python and not PySimpleGUI, I hope it helps people create their own GUI's too.
That being said I already pushed the code :)

**Comment by PySimpleGUI** [comment]
Thanks for letting me off the hook.... still feels a bit pushy to me, but if you're good with it 👍🏼

Congrats on taking the brave step of sharing your creation with the world (I've learned it really is THE WORLD 😉).  PySimpleGUI users are awesome so I can't imagine any of this being a bad experience overall. Nice job of posting an animated GIF in your readme!  It's a fantastic way to get attention and demonstrate what you've done.  Hope you're enjoying the process.  Keep building!
