### ISSUE TITLE
Program crashes if a main.py exists in the same folder with less than 102 lines

### ISSUE THREAD

**Issue by Cheeseypop** [PriestTheBeast/SimpleGUIBuilder#2]
Error: list index out of range

Reproduction steps:
Download latest exe
Make a non blank "main.py" file in the same folder (simply adding a space to the file will do)
Try and launch the program

This will also crash the program if a non-blank main.py file is created while its running and anything is clicked on

However this only applies when the "main.py" file is less than 102 lines long.

Fix:
Building the exe with python 3.9.1 fixes this

**Comment by PriestTheBeast** [comment]
That's some crazy ass bug xD im gonna check it out when I can.

**Comment by PriestTheBeast** [comment]
Well, it was what I expected, a naming conflict because my main file is also called main.py. 
I changed it's name and it's fixed 👍 I'll release the fix soon.
Thx for reporting the error :)
