### ISSUE TITLE
Program crash whenever any node is clicked on

### ISSUE THREAD

**Issue by Dr-Scott-James** [PriestTheBeast/SimpleGUIBuilder#3]
I downloaded your code and run the simple_gui_builder.py file.  The interface comes up and I can preview fine.  If I try to click on any entity like a text field, I get an error "Error: module 'PySimpleGUI' has no attribute 'pin'.  General error.  This error exists so the program doesn't just crash.  An error happened that I didn't catch properly, so no good message to help in what's wrong except the prob bliberish above :("  This happens on the sample layout as well as if I try to create a new layout [] though import.  I like the idea of your project!

**Comment by PriestTheBeast** [comment]
Well, that makes it hard to do anything with SimpleGUIBuilder xD

My guess is this: When you click a node it's properties window is supposed to appear on the right. 
For that to happen it makes a number of things including this
![image](https://user-images.githubusercontent.com/25922992/110114265-43c89d80-7dac-11eb-957f-9104ca9bb257.png)
Therefore from the "Error: module 'PySimpleGUI' has no attribute 'pin'" I'm assuming it didn't found a pin method in the 'PySimpleGUI' module, which could be a version problem with the 'PySimpleGUI' module.

If you don't have the last version of 'PySimpleGUI' pls update it and try again. If the issue persists pls tell me the 'PySimpleGUI' version you are using.
I'm glad you like the idea and I hope you like it after trying it too :)

**Comment by Dr-Scott-James** [comment]
Miguel,

That was it - I updated PySimpleGUI and everything was fine.  Thanks for the tip!  I look forward to working with this.

Regards,

Scott
