### ISSUE TITLE
Malformed nodee or string?

### ISSUE THREAD

**Issue by Nasko-5** [PriestTheBeast/SimpleGUIBuilder#5]
After using the program for a bit it suddenly crashed, showing me this error:
![image](https://user-images.githubusercontent.com/66528033/126428827-508e78df-bb3d-457b-801b-c155f910d503.png)

Reinstalling the program wouldn't work.
As for recreating the error, I have no idea.

**Comment by sxwebster** [comment]
EDIT: Upgraded to Python 3.9+, changed my environment variables to remove references to old Python versions in PATH (including one for Python 2.7, then installed PySimpleGUI via pip again and it seems to work. 

******************

I get this after clicking anything at all after the program opens. Not sure if it's perhaps path related. 

C:\Users\i5-Desktop\Downloads\SimpleGUIBuilder-main\SimpleGUIBuilder-main\SimpleGUIBuilder

Python 3.7.7

**Comment by PriestTheBeast** [comment]
I have no clue as to why, maybe with an export of the layout being used, but other people don't seem to have this problem and I have no way to recreate this.

Try to delete the autosave.txt, so if it's a layout problem, it just doesn't keep loading the problematic layout, and resets it.
Hope it helps.
